blank_issues_enabled: false
contact_links:
  - name: Ask a question or get help
    url: https://github.com/ControlFront/controlfront-docs/discussions
    about: Ask a question or request general support in Discussions
