blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a question or get help
    url: https://github.com/controlfront/controlfront-docs/discussions
    about: Use GitHub Discussions for general questions or community support.
