name: ControlFront Scan
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run ControlFront scan
        run: npx -y controlfront-cli@latest scan --project-root "${{ github.workspace }}" --non-interactive
        env:
          CONTROLFRONT_APP_URL: ${{ secrets.CONTROLFRONT_APP_URL }}
          CF_ORG_ID: ${{ secrets.CF_ORG_ID }}
          CF_PROJECT_ID: ${{ secrets.CF_PROJECT_ID }}
      - name: Sync audit to ControlFront
        run: npx -y controlfront-cli@latest sync
        env:
          CONTROLFRONT_APP_URL: ${{ secrets.CONTROLFRONT_APP_URL }}
          CF_ORG_ID: ${{ secrets.CF_ORG_ID }}
          CF_PROJECT_ID: ${{ secrets.CF_PROJECT_ID }}
