name: ControlFront Scan (DEV)
permissions:
  actions: write
  contents: read
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"
  workflow_dispatch:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run ControlFront scan (CI mode)
        run: npx -y @controlfront/cli@latest scan
        env:
          NEXT_PUBLIC_APP_URL: https://cf-dev-x8a9k2h1r7v3pzq5.ngrok.app
          CF_ORG_ID: b85dfc0f-8310-4002-85d6-e501a8601088
          CF_PROJECT_ID: 5d1b2723-1deb-418f-84e0-6c318e0333af
          CF_CI_MODE: "true"
          CF_INGEST_TOKEN: iURFryn-FnHGry-BqNj87KNtKH_e2S5UmsdnThoiKVQ